### ISSUE TITLE
does the URL support defining ports?

### ISSUE THREAD

**Issue by aristosv** [asuknath/Nagios-Status-JSON#10]
When I configure ServerAlarms app on iOS, and use the internal URL (http://192.168.1.17/nagios/), everything is working just fine.

When I open up the server from the internet (http://my.hostname.wan:8080/nagios/), I get a message saying  

```
Certificate Error!
The certificate for this server is invalid. Currently ServerAlarms app is not supporting invalid SSL certificated Please use http: instead of https:
```

I am not using https: though, so my suspicion is that maybe the app doesn't support defining ports in the URL?

I just want to clarify that http://my.hostname.wan:8080/nagios/ is accessible from the internet and I can see my nagios web interface just fine.

**Comment by asuknath** [comment]
I am working to allow non SSL server.

Asuk

**Comment by aristosv** [comment]
Hi, any estimate on when will this work? I really need too provide outside access without VPN.

**Comment by aristosv** [comment]
When using an IP (public or internal) this works just fine. The issue is when using a hostname.

**Comment by asuknath** [comment]
Yes.
