### ISSUE TITLE
Crash when enabling push notifications on Android app

### ISSUE THREAD

**Issue by JZXPacky** [asuknath/Nagios-Status-JSON#11]
Hi Asuk, I've been using the app for some time now and I've started getting an issue where I can't enable push notifications after they disabled themselves. This has been working for some time up until a few days ago.

Whenever I try and turn the push notifications on, the app crashes. I have tried wiping the cache for the app and re-installing but now I can't even configure the app without it crashing. When I add the settings then choose Test & Update it crashes. I am using a Samsung S9+ running Android 8.0.

I've also tried emailing the support address multiple times but have been getting bounce backs. After checking your domain name, I've found there is no MX record configured so you will not receive any email.

I'm the same guy that has been commenting about the time zone issue also. The app is using GMT for some reason but I am in GMT+10 and this is what is configured on my device.

![screenshot_20180219-111949 10](https://user-images.githubusercontent.com/26926362/39389906-98e6b4bc-4ad0-11e8-92bf-43252ffdeef5.jpg)

Hoping you can provide some feedback on this as the app is unusable now.

**Comment by JZXPacky** [comment]
I've just tested the command that the script executes in my browser and am getting the below error. There appears to be an issue with your servers.

Here's the command I ran.
`https://serveralarms.com/fcm/api.php?tag=send&title=%3A%3ACRITICAL%3A%3A+Test_Host&groupname=xxxxx-xxxxx-xxxxx-xxxxx&mess=HOST+-+Test_Host+is+CRITICAL`

Here's the error.
```Warning: mysql_connect(): Host '72.52.114.80' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts' in /var/www/html/fcm/api_connect.php on line 15```

```Warning: mysql_num_rows() expects parameter 1 to be resource, boolean given in /var/www/html/fcm/api_fun.php on line 57```

**Comment by asuknath** [comment]
Going to release an update Monday.

Thanks
Asuk

**Comment by JZXPacky** [comment]
This was resolved with the update.
