### ISSUE TITLE
No data from ServerAlarm 

### ISSUE THREAD

**Issue by wboerhout** [asuknath/Nagios-Status-JSON#12]
Nagios® Core™ 4.2.4, IOS 11.4.1

nath_status.php returns no data in browser:
`{
  "hosts": [
  ],
  "services": [
  ]
} `

and in app, all zeros on dashboard. Used to work fine until recently.

**Comment by asuknath** [comment]
Hi Wilm,

Try to open URL in your computer https://nagiosurl/nagios/nath_status.php
and make sure you are getting JSON output.

Also make sure URL ends with / same as https://nagiosurl/nagios/

- Asuk

**Comment by wboerhout** [comment]
Hmm. That is what I did, and the output is show in my post above. 
Now when I run the same command in the same browser today, it works fine: a long list of JSON output in the browser, and the app shows the expected number of services and hosts with their status.

I do not like it when the behaviour changes without reason, even if it is in the right direction as happened today. It is a problem in the interaction of the script with Nagios, since app and browser behaviour are identical. 

Under what circumstances would the php script return the empty set as shown above? Is there any way to debug the script?

Thanks for the effort, it really is a helpful app/script.

**Comment by IceT-max** [comment]
I found same matter. Check httpd / general log messages, if the status.dat is readable or you found some fopen/fclose errors.

**Comment by asuknath** [comment]
By end of this month I will release a stable version with HA infrastructure.

**Comment by wboerhout** [comment]
project is no longer relevant for me. sorry.
