### ISSUE TITLE
Push notification service not working

### ISSUE THREAD

**Issue by cycl0psg** [asuknath/Nagios-Status-JSON#13]
Is there an issue with the push notification services?  I'm not receiving any notification using the same setup that worked a couple of weeks ago

**Comment by JZXPacky** [comment]
I'm having the same issues, although it is only affecting my Android phone after I disabled push notifications while I was on holidays. Since then when I turn it back on I get nothing. They are working fine on my iPad however.

**Comment by asuknath** [comment]
Going to check now.

**Comment by asuknath** [comment]
Just pushed an update version 1.3.0. Please wait for to available in the Google Play Store.

**Comment by JZXPacky** [comment]
Just updated and confirmed they are working for me now. Have a backlog of notifications coming through for the last month.

**Comment by cycl0psg** [comment]
Thank you, that fixed it.

**Comment by JZXPacky** [comment]
Having issues with this again, stopped working yesterday. Have tried multiple times and have rebooted server etc.

**Comment by JZXPacky** [comment]
I'm assuming something was fixed as it is working now.
